---
title: "cleaning-and-wrangling"
format: html
editor: visual
---

```{r}
#! message: false

# load packages
library(dplyr)
library(tidyr)
library(readr)
```

## Read in our data
```{r}
catch_original = read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")
```

## Explore
```{r}
# colnames(catch_original)

# head(catch_original)

# summary(catch_original)

# unique(catch_original$Region)

# View()
```

# Clean and reshape data
```{r}

```

## Using select() function
```{r}
catch_data = catch_original %>% 
  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)
head(catch_data)

catch_data = catch_original %>% 
  select(-All, -notesRegCode)
head(catch_data)
```

## check column types
```{r}
glimpse(catch_data)
```

## Replace values in a column

```{r}
# change chinook column to numeric

catch_clean = catch_data %>% 
  mutate(Chinook = as.numeric(Chinook))
```

```{r}
# find NA values
is.na(catch_clean$Chinook)

i = which(is.na(catch_clean$Chinook))
i

catch_data[i,]

catch_clean = catch_data %>% 
  mutate(Chinook = if_else(condition = Chinook =="I", 
                           true = "1", 
                           false = Chinook), 
         Chinook = as.numeric(Chinook))
catch_clean[i,]
```


## Reshaping
```{r}
catch_long = catch_clean %>% 
  pivot_longer(cols = -c(Region, Year), 
               names_to = "species", 
               values_to = "catch")
head(catch_long)
```

```{r}
catch_wide = catch_long %>% 
  pivot_wider(names_from = species, 
              values_from = catch)
head(catch_wide)
```

## rename columns with rename()
```{r}
catch_long = catch_long %>% 
  rename(catch_thousands = catch)
head(catch_long)
```

```{r}
catch_long = catch_long %>% 
  mutate (catch = catch_thousands * 1000)
head(catch_long)
```

## Summary stats using group_by() and summarize()
```{r}
# get average catch by region
mean_region = catch_long %>% 
  group_by(Region) %>%
  summarise(mean_catch = mean(catch))

head(mean_region)
```

```{r}
n_region = catch_long %>% 
  group_by(Region) %>% 
  summarise(n = n())

head(n_region)
```

## Filtering rows using the filter()
```{r}
sse_catch = catch_long %>% 
  filter(Region == "SSE")
head(sse_catch)
  
```
```{r}
catch_million = catch_long %>% 
  filter(catch > 1000000)
head(catch_million)
```


```{r}
sse_chinook = catch_long %>% 
  filter(Region == "SSE" & species == "Chinook")
head(sse_chinook)
```

## Sorting data using arrange()
```{r}
mean_region = catch_long %>% 
  group_by(Region) %>% 
  summarise(mean_catch = mean(catch)) %>% 
  arrange(mean_catch)
head(mean_region)

mean_region = catch_long %>% 
  group_by(Region) %>% 
  summarise(mean_catch = mean(catch)) %>% 
  arrange(desc(mean_catch))
head(mean_region)
```


## split and combine values in columns
```{r}
sites_df = data.frame(site = c("HAW-101",
                                "HAW-103",
                                "OAH-320",
                                "OAH-219",
                                "MAU-039"))
head(sites_df)

split_df = sites_df %>% 
  separate(site, c("island", "site_number"), "-")
head(split_df)
```
## cities example
```{r}
cities_df <- data.frame(city = c("Juneau AK",
                                 "Sitka AK",
                                 "Anchorage AK"))

split_cities_df = cities_df %>% 
  separate(city, c("city", "state", " "))
head(split_cities_df)
```

```{r}
date_df = data.frame(
  year = c("1930", "1930", "1930"),
  month = c("12", "12", "12"),
  day = c("14", "15", "16")
)
head(date_df)

dates_unite = date_df %>% 
  unite(date, year, month, day, sep = "-")
head(dates_unite)
```


## pull it all together! 

```{r}
catch_original <- read_csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", 
                               method = "libcurl"))

mean_region <- catch_original %>%
  select(-All, -notesRegCode) %>% 
  mutate(Chinook = ifelse(Chinook == "I", 1, Chinook)) %>% 
  mutate(Chinook = as.numeric(Chinook)) %>% 
  pivot_longer(-c(Region, Year), 
               names_to = "species", 
               values_to = "catch") %>%
  mutate(catch = catch*1000) %>% 
  group_by(Region) %>% 
  summarize(mean_catch = mean(catch)) %>% 
  arrange(desc(mean_catch))

head(mean_region)

```

















